version: '3.8'

services:
  emotion-db:
    image: postgres:15
    container_name: emotion-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - emotion-net

  django-emotion:
    build: .
    container_name: django-emotion
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8008:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - emotion-db
    networks:
      - emotion-net

volumes:
  postgres_data:

networks:
  emotion-net:
    driver: bridge


