version: '3.3'

services:
  emotion-db:
    image: postgres:15
    container_name: postgres-emotion
    env_file:
      - .env              # ✅ .env 파일에서 환경 변수 불러오기
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django-emotion
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8008:8000"
    env_file:
      - .env              # ✅ Django에 .env 주입
    depends_on:
      - emotion-db

volumes:
  postgres_data:

