version: '3.9'

services:
  emotion-db:  # ← 내부 서비스명 수정
    image: postgres:15
    container_name: postgres-emotion
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django-emotion
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8008:8000"
    env_file:
      - .env
    depends_on:
      - emotion-db  # ← 수정됨

volumes:
  postgres_data:
